---

- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox_exporter
  service:
    name: blackbox_exporter
    state: reloaded
  when: systemd_check is defined and systemd_check|succeeded
